### ISSUE TITLE
U8G2LOG change log height

### ISSUE THREAD

**Issue by el-samiyel** [olikraus/u8g2#1132]
Hi excellent library, been my go to for my oled.

I have an issue with changing the log height within the code.

If i call: u8g2log.begin(25, 2, u8log_buffer); the text will no longer print on a new line, however the text is still updated. (only on one line)

It is possible to change the height after the height has already been defined?

Cheers

**Comment by olikraus** [comment]
> It is possible to change the height after the height has already been defined?

The height also spezifies the size of the buffer. I mean in your case, the u8log_buffer must point to a memory with 50 bytes. You can not increase the height without providing a bigger buffer size.
Reduction should work instead.
Example

```
uint8_t buf[50];
...
u8g2log.begin(25, 2, buf);
```

I think you can do another call to ".begin()" at any time, but you must provide a suitable buffer. So

```
u8g2log.begin(25, 3, buf);
```
will not work, because this will lead to a buffer overflow with unpredictable results.
Instead you must provide a bigger buffer:
```
uint8_t buf2[75];
...
u8g2log.begin(25, 3, buf2);
```
Buf if you do so, the previous buffer memory is not used any more, but still will be present in your controller. All in all it doesnt make sense to change the buffer later.
