### ISSUE TITLE
Retrieve vars inside picture loop

### ISSUE THREAD

**Issue by mrueppell** [olikraus/u8g2#1144]
Hi, 
I hope it is okay to ask these two questions here...

I have a little project with 128x64 SSH1106 1,3 inch OLEDs. These OLEDs display short texts a at defined position serving as a label for nearby physical buttons. Depending on button inputs, the text can change or be inverted to show the buttons current state. I started with 8x8 and just changed the part of the display that needed updating/inverting which worded nicely. But then I wanted a really tall and slim font (and non monospace) to get as many characters per line as possible, so I changed to u8g2. Because I am using a sparkfun pro micro (small memory) I cannot use full buffer mode and I am stuck with the famous picture loop that I do not fully understand, despite reading on it (the links provided by the u8g2 tutorial).

Now my question: 
Is it NOT possible to retrieve data dynamically within the picture loop, right? In the example below, I define all variables before the picture loop, but it would be much more efficient to call a function "drawParts" from within the picture loop that retrieves these info from global arrays. That would mean a for loop inside the picture loop that "constructs" everything to display. The for loop would produce the same output every time picture loop runs. Would that be possible or not? Or am I missing something here and there would be a much easier way to go?

```
void DrawAll(SomeInput) {
  bool IsInverted1 = false;
  bool IsInverted2 = false;
  char DispStr1 = "Text1";
  char DispStr2 = "Text2";
  byte PosX1 = 1;
  byte PosX2 = 3;
  byte PosY1 = 2;
  byte PosY2 = 4;

  u8g2.firstPage();
  do {
    u8g2.setFont(u8g2_somefont);

    u8g2.setDrawColor(IsInverted1);
    u8g2.drawStr(PosX1, PosY1, DispStr1);
    u8g2.setDrawColor(IsInverted2);
    u8g2.drawStr(PosX2, PosY2, DispStr2);
  } while ( u8g2.nextPage() );
};
```

Alternative idea:

```
void DrawAll(SomeInput) {
  u8g2.firstPage();
  do {
    for (k = 0; k > 16; k++) {
      DrawParts(SomeInput)
    }
  } while ( u8g2.nextPage() );
};

void DrawParts(SomeInput) {
  // retrieve information from global arrays here
  // set the fonts
  // draw the strings
}
```

Any help is much appreciated! And thanks for the great library!!!
Max

**Comment by olikraus** [comment]
Ok, difficult to read, because we need to agree an some terms first.
"dynamic data": 
I assume with "dynamic data" you meann, data, which changes at any time unexpectedly, such as sensor values. So let me use sensor values instead.

"define variables": I will assume you mean value assignment.

> Is it NOT possible to retrieve data dynamically within the picture loop, right? 

It is very much possible to read (retrieve) sensor values at any time. However you should not use those variables in the picture loop, it could be like this:

``` C++
  int new_value;
  int old_value;
  u8g2.firstPage();
  do {
     new_value = sensor();
     draw(old_value);
    }
  } while ( u8g2.nextPage() );
  old_value = new value;
```
Of course this code does not make much sense because many new_values are just overwritten, but it might be usefull if you do oversampling with a suitable lowpass filter:

``` C++
  int new_value;
  int old_value;
  u8g2.firstPage();
  do {
     new_value = lowpass(new_value, sensor());
     draw(old_value);
    }
  } while ( u8g2.nextPage() );
  old_value = new value;
```

Again, there usually is a more simpler form, if oversampling is not required:
``` C++
  int value = senser();
  u8g2.firstPage();
  do {
     draw(value);
    }
  } while ( u8g2.nextPage() );
```
This is the most simple form and I think, this is what you have implement already. 

> That would mean a for loop inside the picture loop that "constructs" everything to display. 

Sure, very much possible. I think most of the more complex examples for u8g2 will do exactly this.
