### ISSUE TITLE
Stuck pixel using u8g2

### ISSUE THREAD

**Issue by wanrulez** [olikraus/u8g2#1184]
Hello,

I'm a bit newbie.
Im starting using this library since my oled monochrome couldn't detect i2c address.
It work for displaying, however there is stuck pixel.
Could you please help me.

![IMG20200508082549](https://user-images.githubusercontent.com/64995503/81357636-cb9b3800-9106-11ea-9c67-fa2bd02d7d5f.jpg)

**Comment by olikraus** [comment]
Did you use a SSD1306 constructor? This is probably wrong, this looks like a SH1106 display.

**Comment by wanrulez** [comment]
Owh thank you, but how do you identified it was SH1106 display? Sry im newbie.. Thank you very much

**Comment by olikraus** [comment]
:-D Because of the pixel columns on the right. The difference between SSD1306 and SH1106 are exactly those pixel columns. There are many discussions on this problem, especially, because those displays are sold as SSD1306 but are actually SH1106, e.g. here:
https://www.eevblog.com/forum/beginners/problem-with-ssd1306-oled/

**Comment by wanrulez** [comment]
Ok thnx you very much..
