### ISSUE TITLE
ST75256 100x160 LCD display 

### ISSUE THREAD

**Issue by BenW5122** [olikraus/u8g2#1315]
Hi, 

I am trying to run the example codes you provided, but im using a 100x160 LCD display. 
May i know what changes do i need to make to make my display work ?

**Comment by olikraus** [comment]
The ST75256 is already supported, but not your specific dimensions. The first step is to identify an existing constructor, which works correctly. Use the flip mode example and test the some of them: https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#st75256-jlx256128

In probably all cases you will either see no pixel or all pixel enabled. This is due to the very small contrast window of the ST75256 display, so you need to adjust the contrast first (setContrast command).
Maybe start with "U8G2_ST75256_JLX172104_1_4W_SW_SPI, figure out the contrast value (maybe with help of contrast example programm) and check whether the text is displayed correctly.
If the text is not displayed correctly try a different constructor.

You could also post pictures here.

**Comment by olikraus** [comment]
no further response, closing...
