### ISSUE TITLE
[Question] Problems with U8x8 constructor

### ISSUE THREAD

**Issue by danielcalvogonzalez** [olikraus/u8g2#1375]
Hello, I am not sure if this is the right place. If it is not, please let me know where I should address this question.

I'm planning to connect an OLED display based on SH1106 to an ESP8266 nodemcu board. But before doing that and in order to gain confidence, I started by using a simple Arduino UNO board and the same OLED display from Banggood (https://www.banggood.com/1_3-Inch-4Pin-White-OLED-LCD-Display-12864-IIC-I2C-Interface-Module-p-1067874.html?rmmds=myorder&cur_warehouse=CN)

After reading the documentation I decided to use the U8x8lib as my requirements were very basics. I connected both boards and I used the following constructor:

U8X8_SH1106_128X64_NONAME_HW_I2C oled(U8X8_PIN_NONE);

And everything went perfect. I was able to see my text on the screen while I was using PINs A4 and A5 from my Arduino UNO to connect SDA and SCL. So far, so good.

After that, **_without changing any wire_**, I decided to use the full constructor by adding the clock and data PIN numbers. And that's when the funny part began. No matter what numbers I use as clock and data pin numbers, the program always works when I think, it doesn't have to, as I'm using wrong pin numbers.

For instance, 

U8X8_SH1106_128X64_NONAME_HW_I2C oled(U8X8_PIN_NONE, 14, 15);

works. So maybe I'm wrong or maybe I missed an important part or I'm becoming crazy but it seems that the library is not using the clock and data pin indicated in the constructor when it attemps to communicate with the OLED and keeps using the right one.

Would someone kindly shed some light?

Thank you very much.

**Comment by olikraus** [comment]
There are possible data transfer methods to the display. This method is appended to the display name. In your case this is "HW_I2C", which denotes that data should be sent according to the I2C protocol using the uC HW I2C subsystem.
Another method is "SW_I2C" which will use the same protocol, but u8g2 will not use the uC I2C subsystem to transfer the data, insted the protocol is emulated via software gpio only. One advantage of the the SW I2C is this: You can choose any pins.
Coming back to the HW I2C: There are two types of uC: Systems where the I2C pins are fixed (like the AVR systems) and systems where the HW I2C pins can be remapped to any pin (like ESP-uC).
So there are basically three cases:
 * HW I2C with fixed pins: U8X8_SH1106_128X64_NONAME_HW_I2C oled(U8X8_PIN_NONE);
 * HW I2C with pin remapping: U8X8_SH1106_128X64_NONAME_HW_I2C oled(U8X8_PIN_NONE, 14, 15); Note: On AVR (Arduino Uno) the two numbers are ignored, because pin remapping is not possible (pins are fixed)
 * SW I2C, which will be slower, but any pin on any system can be used: U8X8_SH1106_128X64_NONAME_SW_I2C oled(14, 15, U8X8_PIN_NONE);
