### ISSUE TITLE
UC1601 - "Constructor does not name a type"

### ISSUE THREAD

**Issue by letshin** [olikraus/u8g2#1665]
When including

``
U8X8_UC1601_128X64_8080 u8x8(25, 26, 27, 14, 12, 13, 4, 2, 32, 23, 18, 19);
``

into the start of the HelloWorld example the following error returns

``
HelloWorld:219:1: error: 'U8X8_UC1601_128X64_8080' does not name a type
U8X8_UC1601_128X64_8080 u8x8(25, 26, 27, 14, 12, 13, 4, 2, 32, 23, 18, 19);
 ^
``
while compiling. This constructor was obtained from https://github.com/olikraus/u8g2/wiki/u8x8setupcpp. Not sure what is going on - any advice please? The device being used is:

https://uk.rs-online.com/web/p/lcd-monochrome-displays/1247537/ on an ESP32.

Edit 1: Using u8g2 v 2.27.6 Checked U8glib.h and cannot find reference to U8X8_UC1601_128X64_8080 in it. clib folder contains "u8g_dev_uc1601_c128032.c" which is a 128x32 setup, but not 128x64 so I guess this might not be implemented. Can I downgrade to a version that supports 128x64 for the UC1601 please - which version would do this?

**Comment by olikraus** [comment]
Sometimes the error is generated due to a missing object name, but in your constructor line it seems to be available.

The requested constructor is here: https://github.com/olikraus/u8g2/blob/2e7b5be78cf0067043a929ad7dbf6677f2bfc1b3/cppsrc/U8x8lib.h#L5133

There up to date reference should be https://github.com/olikraus/u8g2/wiki/u8x8setupcpp
This also lists your constructor: U8X8_UC1601_128X64_8080 https://github.com/olikraus/u8g2/wiki/u8x8setupcpp#uc1601-128x64

The latest version of u8g2 is 2.31 (https://www.arduinolibraries.info/libraries/u8g2)

**Comment by letshin** [comment]
Sorry & thanks. I think this was because I had installed u8x8 earlier and the script must have been loading the older .h file instead of the one in the u8g2 library. Deleting the u8x8 folder and restarting the IDE meant that I have no issues uploading the code now!
