### ISSUE TITLE
SDL with c++

### ISSUE THREAD

**Issue by shlyakpavel** [olikraus/u8g2#1877]
Is it possible to use SDL output in c++ code?
I have code that already works with arm linux port and I'd like to make it output to SDL for debugging. How can I do that?

**Comment by shlyakpavel** [comment]
There's an SDL platform output in u8g2 https://github.com/olikraus/u8g2/tree/master/sys/sdl
Can I use c++ u8g2 API to use it?

**Comment by olikraus** [comment]
Maybe yes, but I personally have never tried to use the C++ API with the SDL output.
The problem is: There is no C++ API as such. What seems to be an C++ API is actually the Arduino API and the u8g2 project does not include all the Arduino files required for the Arduino API (more specific, the Print base class is missing and of course the other low level functions). So you need to collect some other files from Arduino to make it work.

**Comment by shlyakpavel** [comment]
@olikraus arm-linux has some kind of c++ API that I currently use. I'd like to use the same API for SDL output

https://github.com/olikraus/u8g2/blob/master/sys/arm-linux/examples/cpp-examples/u8g2_4wire_hw_spi_cpp/u8g2_4wire_hw_spi.cpp

**Comment by olikraus** [comment]
Hmmm, this is contributed code, not written by me.

**Comment by shlyakpavel** [comment]
@olikraus I don't mind if someone else notices this issue and helps :)
Let it hang for a while!
