### ISSUE TITLE
alternating lines blank

### ISSUE THREAD

**Issue by Ariffffff** [olikraus/u8g2#189]
I have bought this cheap oled 0.96 inch IIC from aliexpress, its showing alternating lines blank .

Is there a way to check if module is faulty or some coding problem. (so if module is faulty, i dont buy more from same vendor)

I am using this option. 

U8X8_SSD1306_128X64_NONAME_SW_I2C u8x8(/* clock=*/ SCL, /* data=*/ SDA, /* reset=*/ U8X8_PIN_NONE);   // OLEDs without Reset of the Display

 the image came a bit blurry as camera not focusing light, but you can feel the vertical skipped lines, this happened.
![img_20170212_224431](https://cloud.githubusercontent.com/assets/25716599/22864561/98f92526-f175-11e6-9b7d-a3417b96012a.jpg)

![img_20170212_225535 1](https://cloud.githubusercontent.com/assets/25716599/22864609/7e34e486-f176-11e6-97b8-fba10201baa1.jpg)

**Comment by Ariffffff** [comment]
this link might be of help as its saying smothing same, but I have no clue if this is for arduino or what

https://forums.electricimp.com/discussion/2786/ssd1306-oled-128-x-64-display

**Comment by olikraus** [comment]
Thanks for puting the issue here.
Please locate file u8x8_d_ssd1306_128x64_noname.c on your local Arduino library folder.
(reference: https://github.com/olikraus/u8g2/blob/master/csrc/u8x8_d_ssd1306_128x64_noname.c)

In line 61 you find this command:
 U8X8_CA(0x0da, 0x012), 

Please change this value to 
 U8X8_CA(0x0da, 0x002), 

Will this solve the problem?
You can also try
 U8X8_CA(0x0da, 0x022), 

and maybe also:
 U8X8_CA(0x0da, 0x032), 

Will any of these values solve the problem?
Thanks

**Comment by Ariffffff** [comment]
here are my results.


U8X8_CA(0x0da, 0x012),
![x012](https://cloud.githubusercontent.com/assets/25716599/22876977/0a8a1be4-f1f5-11e6-8a73-62e0cae5a673.jpg)


Please change this value to
U8X8_CA(0x0da, 0x002),
visibility gets better, 
![x002](https://cloud.githubusercontent.com/assets/25716599/22876991/1c6c06c4-f1f5-11e6-8ac9-db5266612c4e.jpg)


U8X8_CA(0x0da, 0x022),
![x022](https://cloud.githubusercontent.com/assets/25716599/22876993/2448ec4a-f1f5-11e6-8b7c-4c1ac842de2d.jpg)

U8X8_CA(0x0da, 0x032),
gets more bad

**Comment by Ariffffff** [comment]
I think this might be a manufacturing fault. In my next cart from aliexpress I will retry from other vendor.

**Comment by olikraus** [comment]
Yes, agree, looks like a hardware problem.

**Comment by Ariffffff** [comment]
Thankyou for time and effort
