### ISSUE TITLE
Cannot control menus with something other than buttons

### ISSUE THREAD

**Issue by warriorCavt** [olikraus/u8g2#2003]
Hi there!
In U8G2, we all know that we can't control U8G2 menus with something other than buttons.
This need change.

So we create some global booleans:
```bool u8g2_is_select = false;
bool u8g2_is_left = false;
bool u8g2_is_right = false;
bool u8g2_is_up = false;
bool u8g2_is_down = false;
bool u8g2_is_cancel = false;
```
And there would be a function like: 
```u8g2.setMenuControls(u8g2_is_select, u8g2_is_left, u8g2_is_right, u8g2_is_up, u8g2_is_down, u8g2_is_cancel);```
So when the variable is true, menu is doing the right thing that is in the specific argument of that new function.
Then there will be possibility to control menus with e.g. IR pilot, or joystick and two buttons. 

And maybe make functions that trigger these menu actions. E.g. ```u8g2.menuAction(U8G2_MENU_ACTION_RIGHT /* or something like that */);``` .

And there can stay `u8g2.begin();` with it's pin arguments.

**Comment by olikraus** [comment]
u8g2 never had been planned as a menu system. The existing button functionality is more kind of a demo code.

There are menu systems, which do build on top of u8g2 like [Ardumenu](https://github.com/neu-rah/ArduinoMenu).

There is also an experimental addon called MUI (https://github.com/olikraus/u8g2/issues/1747) , which is part of u8g2 since some time. MUI was designed to deal with events instead of buttons and includes demo code to map for example rotary encoder data to those events: 
https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/MUIInputSimpleRotary/MUIInputSimpleRotary.ino

MUI is fully functional and almost stable, but I didn't yet release MUI officially. But it is there and the existing code can be used:
https://github.com/olikraus/u8g2/wiki/muiref
https://github.com/olikraus/u8g2/wiki/muimanual

Example code is here (Look for prefix MUI): https://github.com/olikraus/u8g2/tree/master/sys/arduino/u8g2_page_buffer
