### ISSUE TITLE
Restrict render part for ST7565 and vertical position

### ISSUE THREAD

**Issue by grzegorzbanas** [olikraus/u8g2#2064]
Hello, how can I restrict sending data to display RAM for vertical (portrait mode) position?
In default orientation I can count page buffers and fix it like this:
```
    uint8_t lcd_page = 0;
    lcd.firstPage();
    do {
        if (lcd_page == 4) {
            lcd.drawStr(0, 45, "U8G2");
        }
        lcd_page++;
    } while (lcd.nextPage());```

**Comment by olikraus** [comment]
> can I restrict sending data to display RAM for vertical (portrait mode) position?

The quick anwser is: No, you can not do this.

Remarks for a longer answer:
 * The content of your variable `lcd_page` is available with https://github.com/olikraus/u8g2/wiki/u8g2reference#getbuffercurrtilerow . I mean instead of introducing `lcd_page` the current page is returned by that function.
 * The page buffers are a property of the display: They are fixed and will not rotate along with any mode change. As a consequence your example code wouldn't work any more: The page will go from top to bottom instead from left to right.
 * What is your goal? Your question implies, that you want to reduce the data sent to the display. However, this will not happen in your example: The data sent to the display will not be lower if you check for the page. So you just improve speed by avoiding calls to drawStr(). Note: U8g2 will internally check whether the graphics primitives intersect with the buffer. Actual drawing will only happen, if there is a none-empty intersection with the current buffer area, see for example here:  https://github.com/olikraus/u8g2/blob/0e0ec4ee63e59eb58345f0d3d34f2e6435bc6348/csrc/u8g2_box.c#L42-L48
 * In order to reduce the data sent to the display, you need to assign the page value via https://github.com/olikraus/u8g2/wiki/u8g2reference#setbuffercurrtilerow and use sendBuffer command to transfer the page (Using https://github.com/olikraus/u8g2/wiki/u8g2reference#updatedisplayarea might also be an option if you can use the full buffer constructor). Example for using setBufferCurrTileRow is here: https://github.com/olikraus/u8g2/blob/master/sys/arduino/u8g2_page_buffer/UpdatePartly/UpdatePartly.ino
 * Improving the rendering speed is also possible with https://github.com/olikraus/u8g2/wiki/u8g2reference#setclipwindow . This would also work in all modes.
