### ISSUE TITLE
u8g2lib "setInverseFont"

### ISSUE THREAD

**Issue by CodeSpoof** [olikraus/u8g2#2231]
On u8x8lib there's the "setInverseFont" command and I couldn't find something similar in u8g2lib.
I just wanted to ask if there is an equivalent in u8g2 and otherwise ask if one could be added.

**Comment by olikraus** [comment]
Usually you would use drawBox and invert the text. 
You could use drawButtonUTF8() https://github.com/olikraus/u8g2/wiki/u8g2reference#drawbuttonutf8 
This has a inverse option for the text, see example 4.

You can also look into the getStrWidth/getUTF8Width functions. Instead of the frame just use the drawBox command with drawColor 2: https://github.com/olikraus/u8g2/wiki/u8g2reference#getstrwidth
