### ISSUE TITLE
Support for MAX7219 32X32 led matrix

### ISSUE THREAD

**Issue by MrManlu** [olikraus/u8g2#694]
Hello everyone!

I would like to know how I could adapt this library to a 32x32 led matrix based on MAX7219 driver. I have the next board: https://www.amazon.es/AptoFun-Matrix-MAX7219-Display-Arduino/dp/B01LOMZH8C/ref=sr_1_19?s=electronics
which consist in 16 modules connected in series.

I know nowadays the library support a 32x8 matrix, but I would like to know how I could start to develop the support of the whole screen, trying to skip the nerd implementation of defining four devices.

I think the hardest part is to program that the matrix is an square of 4x4 modules, not a long row of 1x16 displays.

I love this library and I follow it since the first version, and i'd like to keep using it with this new display. Thanks for all!

**Comment by olikraus** [comment]
It is a little bit difficult. Maybe impossible.
The problem is this: The complete display RAM has to be written at once. This is a conflict to the base assumption, that it is possible to write individual pixel rows.

Actually I do not know how to implement this.
You could create 4 different u8g2 objects for 32x8 elements each. 
Or I could create a 128x8 device...
But 32x32 will not be possible.

**Comment by MrManlu** [comment]
Okey. Thanks for all!

**Comment by olikraus** [comment]
:-/
