### ISSUE TITLE
KS0713 support

### ISSUE THREAD

**Issue by wchpikus** [olikraus/u8g2#700]
hi
is it possible to add support for this driver?
https://docs-emea.rs-online.com/webdocs/07ee/0900766b807ee715.pdf
KS0713
Regards

**Comment by wchpikus** [comment]
Yes i can.

**Comment by olikraus** [comment]
Great. Then please use the ST7565 driver with your display.

**Comment by wchpikus** [comment]
Hi
What exactly i have to use?
It is loot of st7565;)..
C12864?

**Comment by olikraus** [comment]
> What exactly i have to use?

You have to test by yourself. Try one ofter the other until you find a constructor which fits.
You could also compare the init sequence of your display (which has to be provided by the display vendor) with the init sequence in U8g2, but I think this is even more time consuming compared to just try all of the constructors.

**Comment by wchpikus** [comment]
ok, now i testing all st7565 sw spi

**Comment by olikraus** [comment]
Let us verify that you did the setup correctly:
Which U8g2 constructor did you use? Please provide one example, including the setup with your pins.
How did you connect the Arduino Board with the display? Which wire goes to which pin? Maybe provide a picture of the setup?

What is  JLX1926? I am confused? 

Yes, u8x8_d_st7565.c includes all the different variants.

**Comment by wchpikus** [comment]
Ok i use esp8622 with the same software pins (miso,cs,reset etc ) for driving JLX1926.
So i use the same pins to connect to this lcd.
Connected this way:

U8G2_ST7565_JLX12864_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 14, /* data=*/ 13, /* cs=*/ 15, /* dc=*/ 4, /* reset=*/ 5);  //new lcd


//U8G2_UC1604_JLX19264_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=*/ 14, /* data=*/ 13, /* cs=*/ 15, /* dc=*/ 4, /* reset=*/ 5);

Connect to pins 4,5,14,15,16 in lcd.
Tested with osciloscope and signals connected.

**Comment by olikraus** [comment]
Hmm... I am a library author. I resources to support wiring problems are limited. I can do a review, but then you have to provide *all* information. At the moment this issue looks like this to me:
 * Your display seems to be compatible to ST7565 (verified some days, back but maybe a closer comparison between the ST7565 datasheet and the KS0713 might be required)
 * From the above assumption any driver should at least display something. However, nothing is displayd.
 * This means: Wiring is an issue. But I can not verify your wiring, because of limited information from your side.
 * Finally your provide extra information like JLX1926. This is confusing. I still do not know what you mean by JLX1926. I also do not know why this is related to your problem.

Let me give you a final example: After my questions you provide the following call:
> U8G2_ST7565_JLX12864_F_4W_SW_SPI u8g2(U8G2_R0, /* clock=/ 14, / data=/ 13, / cs=/ 15, / dc=/ 4, / reset=*/ 5); //new lcd

And you say:

> Connect to pins 4,5,14,15,16 in lcd.

What does this mean? Is ESP pin 14 connected to pin 4 of your LCD? If so, then this seems to be wrong according the datasheet you provided above. But actually the information how pins are connected is still missing: You did NOT answer my question about how pins are connected.

And also consider this: I do not get money here, I have to spend my personal resources to support you. It is not very time efficient if I have to repeat questions and ask for every bit of information.

**Comment by wchpikus** [comment]
ok 
connection of lcd.
![20180914_071225](https://user-images.githubusercontent.com/3776183/45531484-3a1fd980-b7f0-11e8-80cb-bafe525358b4.jpg)
![20180914_071240](https://user-images.githubusercontent.com/3776183/45531485-3a1fd980-b7f0-11e8-871d-e41099ba7682.jpg)
![20180914_071251](https://user-images.githubusercontent.com/3776183/45531486-3a1fd980-b7f0-11e8-9bee-2ce1c8fae1c5.jpg)
![20180914_071302](https://user-images.githubusercontent.com/3776183/45531487-3ab87000-b7f0-11e8-8436-018781a01198.jpg)
![20180914_071316](https://user-images.githubusercontent.com/3776183/45531488-3ab87000-b7f0-11e8-9df4-9f42baa496d4.jpg)

"Connect to pins 4,5,14,15,16 in lcd." it is no one by one corresponding to driver, this is only pinout which was connected,

**Comment by wchpikus** [comment]
Hello.
I need to use spi ( no free gpio for this), but it can be done for test.
I thing about that and it can be hardware  setup only for 8080 mode..i make some picture of pcb..but as you wrote,no pin for that (PS).
Later i will send more pictures.

**Comment by wchpikus** [comment]
it could be this...
![20180915_103555](https://user-images.githubusercontent.com/3776183/45584425-855ee880-b8d3-11e8-8591-d8466b75d998.jpg)
![20180915_103606](https://user-images.githubusercontent.com/3776183/45584427-87c14280-b8d3-11e8-8930-cebfe7f8768d.jpg)

**Comment by wchpikus** [comment]
i connect them together now (pin15) is now pull-down..i thing so..

**Comment by olikraus** [comment]
You have to test this display. Basically your display is 64128E. U8g2 has a constructor for the 64128N: U8G2_ST7565_64128N_F_4W_SW_SPI. So you have to test which one fits. First of all you need to be able to see at least something. Please also look from the side, the graphics might be very dimm.

**Comment by wchpikus** [comment]
For now no results...dark all the time (empty screen),only harwdare reset i see.

**Comment by olikraus** [comment]
Hmm... I am running out of ideas.

**Comment by olikraus** [comment]
hmmm.. no solution? 
Closing for now. Feel free to reopen...

**Comment by wchpikus** [comment]
No,sorry, no success to run with this lcd.
I tested with new oled ssd and works ok.

**Comment by olikraus** [comment]
ok...
