### ISSUE TITLE
Support for LS013B4DN04 1.3" 168x144 Monochrome

### ISSUE THREAD

**Issue by Enginerd247** [olikraus/u8g2#745]
Is there any way I can get this display working with u8g2? I already have an OLED display working in my project with u8g2 and it's awesome. I now want to change to a display that is less power hungry. Would it be possible to use u8g2 on this display? LS013B4DN04 1.3" 168x144 Monochrome

Datasheet:
https://cdn-shop.adafruit.com/datasheets/LS013B4DN04-3V_FPC-204284.pdf

**Comment by olikraus** [comment]
Hmm... The datasheet says 96x96 pixel.

**Comment by Enginerd247** [comment]
Odd. I pulled the datasheet from Adafruits website. I found the proper datasheet for this display on DigiKey

https://media.digikey.com/pdf/Data%20Sheets/Sharp%20PDFs/LS013B7DH05.pdf

**Comment by Enginerd247** [comment]
Display from Adafruit's website

https://www.adafruit.com/product/3502

**Comment by olikraus** [comment]
ok, so it is 144x168

**Comment by olikraus** [comment]
I have created beta 2.25.0 with the above mentioned constructors.

You can download the latest U8g2 beta release from here: https://github.com/olikraus/U8g2_Arduino/archive/master.zip
1. Remove the existing U8g2_Arduino library (https://stackoverflow.com/questions/16752806/how-do-i-remove-a-library-from-the-arduino-environment)
2. Install the U8g2_Arduino Zip file via Arduino IDE, add zip library menu (https://www.arduino.cc/en/Guide/Libraries).

**Comment by olikraus** [comment]
Does the LS013B4DN04 work?

> Do you have any plans on adding SSD1673?

Not really. Although I tried to support e-paper, u8g2 was developed with LCDs in mind. There are other libraries which fit better, like https://github.com/ZinggJM/GxEPD2

@ZinggJM is here support for SSD1673 in your lib?

**Comment by ZinggJM** [comment]
GxEPD2 and GxEPD are libraries for e-paper display panels from Dalian Good Display and e-paper displays from Waveshare that use these panels. The libraries are for the Arduino IDE only. And I can support only displays that I have, either bought because of my interest, or donated to me.
An e-paper based on SSD1673 might be similar enough to be added as an exception, or I might create a variant of GxEPD2 for it. A prerequisite is an existing driver or demo source that could be ported with reasonable effort to the Arduino IDE, and any needed connection means to connect it to a suitable Arduino board. U8g2_for_Adafuit_GFX can be used with both libraries; more easily with GxEPD2.

**Comment by olikraus** [comment]
ZinggJM, thank you for the quick answer.

**Comment by olikraus** [comment]
any feedback?

**Comment by Enginerd247** [comment]
It works great! Thank you for getting it implemented.

**Comment by olikraus** [comment]
Thanks!
