### ISSUE TITLE
Make u8g2 more SBC cross platform

### ISSUE THREAD

**Issue by sgjava** [olikraus/u8g2#751]
I've seen Pi demos using u8g2, but I like to make something more cross platform since I have several types of SBCs. I'm the author of https://github.com/sgjava/userspaceio and it allows user space access to GPIO, I2C, SPI, etc. The best part is that it's already cross platform, so I don't have to use hacked up RPi.GPIO or WiringPi libs for each SBC. Also, Userspace IO supports C, C++, Python 3 and Java 8 (and other JDK languages), thus I'd eventually build language wrappers for u8g2 based on the C code.

Where would be a good place to start to start?

**Comment by olikraus** [comment]
The HAL only requires only two callback functions.
1. One callback is required for single bits, signals and delays. It us usually called the GPIO&delay callback
2. The second callback is the byte level transfer procedure. It is only there for speed improvements because using the I2C/SPI subsystem of the controller is much faster than bitbanging procedures. However there are several buildin byte level transfer procedures, which just call the GPIO&delay procedures (which is nothing else than bitbanging) 

Well, the best (and only from my perspective) starting point is here:

https://github.com/olikraus/u8g2/wiki/Porting-to-new-MCU-platform

This will include also some links to external resources (although i have not checked whether they are still available).

There is also a sw architecture overview of the HAL:

https://github.com/olikraus/u8g2/blob/master/doc/u8g2_software_architecture.png

It might be a little bit outdated here and there.

U8g2 is a pure C library. All the code is here: https://github.com/olikraus/u8g2/tree/master/csrc

The C++ interface is just a wrapper around the C code, but adds new byte procedures which map the I2C and SPI protocol to the corresponding Arduino procedures:

https://github.com/olikraus/u8g2/tree/master/cppsrc

Let me know if you have more specific questions.

**Comment by sgjava** [comment]
Cool, thanks. I'll see what I can come up with.
