### ISSUE TITLE
Missing Constructor

### ISSUE THREAD

**Issue by SteveC00k** [olikraus/u8g2#752]
SED1520 122X32
This does not exist except on the constructor list pages
https://github.com/olikraus/u8g2/wiki/u8g2setupcpp

**Comment by olikraus** [comment]
Will sbn1661 work?

**Comment by SteveC00k** [comment]
No the sbn1661 doesn't work as it causes the display to show everything mirrored. I have attempted to use it and even attempted to alter one of the headers as suggested by another to revers things but it does not work.

**Comment by SteveC00k** [comment]
This is the display I have when attempting to use the sbn1661:
![img_9709](https://user-images.githubusercontent.com/995817/48974112-81ea8a80-f003-11e8-8e9c-0b7c88cf264a.JPG)

![img_9711](https://user-images.githubusercontent.com/995817/48974113-87e06b80-f003-11e8-915e-e8ab759b8f0b.JPG)

**Comment by olikraus** [comment]
Regarding your initial post:

> SED1520 122X32
This does not exist except on the constructor list pages

What exactly does this mean? I see the constructor in the examples (at least the full buffer examples).

> No the sbn1661 doesn't work as it causes the display to show everything mirrored.

You display differs from the one which I have used for testing.
You could use the Mirrir option (https://github.com/olikraus/u8g2/wiki/u8g2setupcpp#rotation): Use `U8G2_MIRROR` instead of `U8G2_R0`.

Will this solve your problem?

**Comment by SteveC00k** [comment]
Found out that the hello world example I was using didn't have the SED1520. 
Found another had an example and I copied it. Used the mirror option. The text is oriented correctly but half of the text is chopped off.

**Comment by SteveC00k** [comment]
Ok managed to get the display working. Need to learn more about the lib. Its huge.
